Audit Service zum speichern von Auditeinträgen in der DB
it-at-m/kf-app-eai pull request #6
Opened 2024-05-02 11:35 UTC by itgkarl

**Description**

Implement a service to store the reqest and response this eai gives into the database.
This enables us to monitore the usage and respond to errors.

2024-05-02 12:09 UTC, maximilian-zollbrecht requested changes
Bei den Namen würde ich noch ein paar Sachen ändern.

2024-05-02 12:09 UTC, maximilian-zollbrecht commented on src/test/java/de/muenchen/rbs/kitafindereai/audit/AuditServiceTest.java
> +    public void testStoreReqResEntrieException() {
als Name würde ich `testStoreRequestResponseEntryException` besser finden

2024-05-02 12:09 UTC, maximilian-zollbrecht commented on src/main/java/de/muenchen/rbs/kitafindereai/audit/AuditService.java
> +    private AuditRequestResponseDataRepository reqResRepositroy;
*`reqResRepository`

2024-05-02 12:09 UTC, maximilian-zollbrecht commented on src/main/java/de/muenchen/rbs/kitafindereai/audit/AuditService.java
> +            AuditRequestResponse entrie = new AuditRequestResponse();
Methoden- und Variablenname sollte `...entry` sein.

2024-05-02 12:09 UTC, maximilian-zollbrecht commented on src/main/java/de/muenchen/rbs/kitafindereai/adapter/kitaplaner/KitaFinderService.java
> +                    auditService.storeReqResEntrie(kibigwebId, null, null,
Wenn das geht wäre es vermutlich besser das in `ApiErrorHandlingControllerAdvice` zu handeln. Ansonsten könnten Änderungen sehr leicht zu Inkonsistenzen zwischen DB-Audit und tatsächlichen Antworten führen.

2024-05-02 12:09 UTC, maximilian-zollbrecht commented on src/main/java/de/muenchen/rbs/kitafindereai/audit/model/AuditRequestResponse.java
> +    private String rslvKitaIdExtern;
Was bedeutet `rslv`?

2024-05-02 12:09 UTC, maximilian-zollbrecht commented on src/main/resources/db/migration/V001__Initial_Schema.sql
> +CREATE TABLE AUD_REQ_RES (
Ich hätte lieber einen längeren Namen, der noch sprechender ist.

2024-05-03 10:21 UTC, itgkarl commented on src/test/java/de/muenchen/rbs/kitafindereai/audit/AuditServiceTest.java
> +    public void testStoreReqResEntrieException() {
done

2024-05-03 10:22 UTC, itgkarl commented on src/main/java/de/muenchen/rbs/kitafindereai/audit/AuditService.java
> +    private AuditRequestResponseDataRepository reqResRepositroy;
fixed

2024-05-03 10:23 UTC, itgkarl commented on src/main/java/de/muenchen/rbs/kitafindereai/adapter/kitaplaner/KitaFinderService.java
> +                    auditService.storeReqResEntrie(kibigwebId, null, null,
Umgebaut auf Errorhandler und Controller wie besprochen

2024-05-03 10:25 UTC, itgkarl commented on src/main/java/de/muenchen/rbs/kitafindereai/audit/model/AuditRequestResponse.java
> +    private String rslvKitaIdExtern;
resolve:

An den DB feldern wollte ich anzeigen, dass es drei kategorien an Daten gibt:
request: req (Was wurde angefragt)
response: res (Was haben wir geantwortet)
resolved: rslv (Was haben wir intern aus der Anfrage für Werte reolved --> kitaIdExtern und Träger zur Anfrage ermittelt.

2024-05-03 10:26 UTC, itgkarl commented on src/main/resources/db/migration/V001__Initial_Schema.sql
> +CREATE TABLE AUD_REQ_RES (
Auf AUD_KITA_APP_REQUESTS  angepasst

2024-05-03 11:08 UTC, itgkarl commented
@maximilian-zollbrecht 
Ich habe die Anpassungen durchgeführt. Audit-Logs werden jetzt immer in den Errorhandlern in negativ-Fall oder im Controller beim positiv-Fall geschrieben.

Eine Änderung würde ich dich bitten noch mal abzunehmen:

Ich habe bei den Error-Handlern einen globalen Errorhandler als Fallback für Exception.class eingeführt:
Sonst verlieren wir beim logging alle Requests die eine unerwartete Exception (z.B. Netzwerktimeout bei kommunikation zum kf) ausgelöst haben. Diese werden über diesen globalen Handler bearbeitet.
Der verhindert auch gleichzeitig, dass wir ungefangenen Stacktraces nach drausen geben.

--> Dabei ist mir aufgefallen, dass die bisherigen Error-Handler alle KitaAppApi Controller spezifisch sind.
Auch mein globaler Error Handler für Exception.class ist KitaAppApiController spezifisch da hier versucht wird die Controller spezifische UriTemplate-Variable kibigWebId aus dem Request zu ermitteln um sie im AuditLog nicht zu verlieren.

--> Ich habe daher den ControllerAdvice als spezifischen Errorhandler für unseren KitaAppApiController gesetzt. Der greift also nur noch bei diesem Controller und funkt nicht mehr in unsere InernalApiController hinein.
Am verhalten zu vorher ändert das nichts. Der inerne Contoller hat bislang sowieso nur unbehandelte Exceptions geworfen die durch den Spring default in einen Response mit Trace gesteckt werden.

Verhalten ist dadurch also identisch. Sollte man nur wissen, dass eventuelle ExceptionHandler für den Internen Controller einen eigenen ControllerAdvice benötigen.

2024-05-06 06:56 UTC, maximilian-zollbrecht approved these changes

2024-05-06 06:56 UTC, maximilian-zollbrecht commented on src/main/java/de/muenchen/rbs/kitafindereai/api/KitaAppApiController.java
> +                    @Content(schema = @Schema(implementation = ErrorResponse.class)) })
Das würde ich eher nicht machen, da auch ungecatchte 500er hier rein fallen. Da können wir die Antwort nicht steuern.
Evtl. 500 ein zweites mal aufnehmen mit Void?

2024-05-06 06:56 UTC, maximilian-zollbrecht commented on src/main/java/de/muenchen/rbs/kitafindereai/audit/data/AuditRequestResponse.java
> +    @Size(max = 255)
Hier noch auf 2048 anpassen.

2024-05-06 08:50 UTC, itgkarl commented on src/main/java/de/muenchen/rbs/kitafindereai/api/KitaAppApiController.java
> +                    @Content(schema = @Schema(implementation = ErrorResponse.class)) })
Globaler Errorhandler für den Controller eingeführt. Dieser gibt hier tatsächlich alle 500er mit ErrorResponse zurück. Daher korrekt.

2024-05-06 08:54 UTC, itgkarl commented on src/main/java/de/muenchen/rbs/kitafindereai/audit/data/AuditRequestResponse.java
> +    @Size(max = 255)
done

2024-05-06 08:57 UTC, merged